config/routes.rb
Rails.application.routes.draw do
  resources :listings

  root :to => 'pages#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }

  resources :users, only: [:show]

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  resources :listings do
    resources :reservations, only: [:create]
  end

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/meeting_place' => 'listings#meeting_place', as: 'manage_listing_meeting_place'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  # 必須項目
  validates :category, presence: true
  validates :program_time, presence: true
  validates :program_level, presence: true
  validates :location, presence: true

  geocoded_by :meeting_place
  after_validation :geocode, :if => :meeting_place_changed?

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :listing

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :listings
  has_many :reservations

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = "http://graph.facebook.com/#{auth.uid}/picture?type=large" # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :phone_number, :description])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :update, :basics, :description, :meeting_place, :price, :photos, :calendar, :bankacccount, :publish]

  def index
    @listings = current_user.listings
  end

  def show
    @photos = @listing.photos
  end

  def new
    # 現在のユーザーのリスティングの作成
    @listing = current_user.listings.build
  end

  def create
  # パラメーターとともに現在のユーザーのプログラムを作成
    @listing = current_user.listings.build(listing_params)

    if @listing.save
      redirect_to manage_listing_basics_path(@listing), notice: "プログラムを作成・保存しました"
    else
      redirect_to new_listing_path, notice: "プログラムを作成・保存できませんでした"
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to :back, notice: "更新できました"
    end
  end

  def basics
  end

  def description
  end

  def meeting_place
  end

  def price
  end

  def photos
    @photo = Photo.new
  end

  def calendar
  end

  def bankaccount
  end

  def publish
  end

  private
  def listing_params
    params.require(:listing).permit(:program_level, :category, :program_time, :location, :title, :summary, :language, :price, :time_schedule, :meeting_place, :capacity, :price_include, :to_bring, :active)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    def create
        @photo = Photo.new(photo_params)
        if @photo.save
            render json: { message: "success", photoId: @photo.id }, status: 200
        else
            render json: { error: @photo.errors.full_messages.join(", ") }, status: 400
        end
    end

    def destroy
        @photo = Photo.find(params[:id])
        if @photo.destroy
            render json: { message: "file deleted from server" }
        else
            render json: { message: @photo.errors.full_messages.join(", ") }
        end
    end

    def list
        listing = Listing.find(params[:listing_id])

        photos = []
        Photo.where(listing_id: listing.id).each do |photo|
            new_photo = {
                id: photo.id,
                name: photo.image_file_name,
                size: photo.image_file_size,
                src: photo.image(:thumb)
            }
            photos.push(new_photo)
        end
        render json: { images: photos }
    end

    private
    def photo_params
        params.require(:photo).permit(:image,:listing_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!

  def create
    @reservation = current_user.reservations.create(reservation_params)

    redirect_to @reservation.listing, notice: "予約が完了しました"
  end


  private
    def reservation_params
      # コミッション費等　params.require(:reservation).permit(:date, :adults, :children, :infants, :participants, :price, :commission, :total_price, :listing_id)
      params.require(:reservation).permit(:date, :price, :total_price, :participants, :listing_id)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id]) #Userモデルから、userを探してきた。
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(controller)
      controller.include?(params[:controller])
  end

  def action?(action)
      action.include?(params[:action])
  end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WellnessGuide</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>

    <!-- flashにメッセージがある時 -->
    <% unless flash.empty? %>
    	<script type="text/javascript">
    		<% flash.each do |f| %>
    			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
    			toastr['<%= type %>']('<%= f[1] %>');
    		<% end %>
    	</script>
    <% end %>

  </body>
</html>

app/views/listings/basics.html.erb
<!-- 基本情報編集ページ -->
<%= render 'partial/navbar' %>
<div class="container">
    <div class="col-md-3">
        <!-- vertical-navbar -->
        <%= render 'partial/verticalnavbar'%>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">
              <div class="text-center">
                  <span style="font-size:24px;">基本情報の編集</span>
              </div>
          </div>

          <div class="panel-body">
              <%= form_for @listing do |f| %>
                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                              <label>カテゴリー</label>
                              <%= f.select :category, [["フィジカル","フィジカル"], ["メンタル","メンタル"], ["ビューティ","ビューティ"], ["フード","フード"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
                      <div class="col-md-12 select">
                          <div class="form-group">
                            <label>所要時間</label>
                            <%= f.select :program_time, [["２時間以内","２時間以内"],["２時間以上","２時間以上"],["数日間","数日間"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
                          </div>
                      </div>
                  </div>
                  <br>

                  <div class="row">
      							<div class="col-md-12 select">
      								<div class="form-group">
      									<label>レベル</label>
      									<%= f.select :program_level, [["上級","上級"],["中級","中級"],["初級","初級"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
      								</div>
      							</div>
      						</div>
      						<br>

      						<div class="row">
      							<div class="col-md-12 select">
      								<div class="form-group">
      									<label>ロケーション</label>
      									<%= f.select :location, [["屋内","屋内"],["屋外","屋外"]], {prompt:"選択してください"}, {required: 'true', autofocus: 'true', class: 'form-control'} %>
      								</div>
      							</div>
      						</div>
      						<br>

                  <div class="actions">
                      <%= f.submit "更新", class: "btn btn-danger" %>
                  </div>
              <% end %>
          </div>
      </div>
  </div>
</div>

app/views/listings/calendar.html.erb
<%= render 'partial/navbar' %>
<div class="container">
  <div class="col-md-3">
    <!-- vertical-navbar -->
      <%= render 'partial/verticalnavbar'%>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="text-center">
          <span style="font-size:24px;">Calendar</span>

        </div>
      </div>

      <div class="panel-body">

        <!-- datepicker Calendar -->
        <%= form_for([@listing, @listing.reservations.new]) do |f| %>
          <div class="row row-space-top-4">
            <div class="col-md-8 col-md-offset-2 calendar">
              <label>開催しない日にちを指定する</label>
              <div id="datepicker"></div>
            </div>
          </div>
          <br>
          <hr>

          <!-- 隠し要素として"listing_id"をおくる -->
          <%= f.hidden_field :listing_id, value: @listing.id %>
          <%= f.hidden_field :selectedDates, value: "",id:"selectedDates" %>


          <div class="actions">
            <%= f.submit "更新", class: "btn btn-danger" %>
          </div>

        <% end %>

      </div>
    </div>
  </div>
</div>

<script>

// http://stackoverflow.com/questions/1452066/jquery-ui-datepicker-multiple-date-selections
// 上のurlを参照

//他人がした予約日
disabledDates = [];

//自分が予約した日付
selectedDates = [];

function addDate(date) {
  if ($.inArray(date, selectedDates) < 0) {
    selectedDates.push(date);
  }
}

function removeDate(index){
  //splice(削除開始位置,削除する要素数)
  selectedDates.splice(index,1);
}

// 選択された日付がすでに"selectedDates"にあれば、削除。なければ追加
function addOrRemoveDate(date) {
    var index = jQuery.inArray(date, selectedDates);
    if (index >= 0)
      removeDate(index);
    else
      addDate(date);
}

// カレンダーの選択可能日と不可能日を決める関数
function SelectMultipleDates(date){
  //inArray(value,array) 第一引数に渡した値が配列中にあれば、そのインデックスを返します。
  var gotDateIndex = $.inArray($.datepicker.formatDate($(this).datepicker('option', 'dateFormat'), date), selectedDates);
  var disabledDateIndex = $.inArray($.datepicker.formatDate($(this).datepicker('option', 'dateFormat'), date), disabledDates);

  if (gotDateIndex >= 0) {
    return [true,'class-holiday'];
  }else if(disabledDateIndex >= 0){
    return [false,''];
  }else{
    return [true, ""];
  }
}

// メインの処理　
$(function () {
  $.ajax({
    url: '/setdate',
    // this data is data for sending to url
    data: {'listing_id': <%= @listing.id %>},
    dataType: 'json',
    // callback argument: data is the response data
    success: function(data){

      $.each(data,function(arrID,arrValue){
        //自分で予約した日付"selectedDates[]"と他人が予約した日付"disabledDates[]"をわけてpushしなきゃいけない
        for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1 )){

          // 自分で予約した場合の日付
          if(arrValue.user_id == <%= current_user.id %>){
            selectedDates.push($.datepicker.formatDate('d-m-yy',d));
            $('#selectedDates').val(selectedDates);
          }else{
            disabledDates.push($.datepicker.formatDate('d-m-yy',d));
          }
        }
      });

      $("#datepicker").datepicker({
          dateFormat: "d-m-yy",
          minDate: 0, // Unix timestamp
          beforeShowDay:SelectMultipleDates,
          onSelect: function(dateText, inst){
              addOrRemoveDate(dateText);
              $('#btn-book').attr('disabled', false);
              $('#selectedDates').val(selectedDates);
              //ruby controller 内で　, で区切って配列化
              console.log("セレクト");
              console.log(selectedDates);
              console.log("ディスエイブル");
              console.log(disabledDates);
          }
      });
    }
  });
});
</script>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/show.html.erb
<%= render 'partial/navbar' %>

<!-- ジャンボトロン -->
<div class="jumbotron row-space-0" style="margin-top: -20px; background: none;">

  <!-- カルーセル -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- リストの点 -->
    <% if @photos.length > 1 %>
      <ol class="carousel-indicators">
        <% @photos.each do |photo| %>
            <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
        <% end %>
      </ol>
    <% end %>

    <div class="carousel-inner" role="listbox">
      <% if @photos %>
        <% @photos.each do |photo| %>
          <div class="item <%= 'active' if photo.id == @photos[0].id %>">
            <%= image_tag photo.image.url(),style: "height:420px; width:100%; overflow:hidden;" %>
          </div>
        <% end %>
      <% end %>
    </div>

    <!-- 左右の矢印 -->
    <% if @photos.length > 1%>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    <% end %>
  </div>

</div>

<!-- サマリー -->
<div class="container-fluid container-listing-show">
    <div class="container">
        <div class="listing-summary row-space-3 row-space-top-3">
            <div class="row">
                <div class="col-md-3 text-center row-space-2">
                    <%= link_to user_path(@listing.user) do %>
                        <%= image_tag @listing.user.image,class:"img-circle profile-2" %>
                    <% end %>
                    <h5><%= @listing.user.name %></h5>
                </div>
                <div class="col-md-6">
                    <div class="listing-title" style="font-size:24px;">
                        <%= @listing.title %>
                    </div>
                    <div class="row row-space-top-4">
                      <div class="col-sm-3 col-xs-3 text-center">
                        <i class="fa fa-heartbeat fa-3x"></i>
                        <h5><%= @listing.category %></h5>
                      </div>
                      <div class="col-sm-3 col-xs-3 text-center">
                        <i class="fa fa-group fa-3x" aria-hidden="true"></i>
                        <h5><%= @listing.program_level %></h5>
                      </div>
                      <div class="col-sm-3 col-xs-3 text-center">
                        <i class="fa fa-clock-o fa-3x" aria-hidden="true"></i>
                        <h5><%= @listing.program_time %></h5>
                      </div>
                      <div class="col-sm-3 col-xs-3 text-center">
                        <i class="fa fa-map-marker fa-3x" aria-hidden="true"></i>
                        <h5><%= @listing.location %></h5>
                      </div>
                    </div>
                </div>

                <!-- 予約フォーム -->
                <div class="col-md-3">
                    <div class="panel panel-default panel-show">
                        <div class="panel-heading">
                                <span style="font-size:16px;"><%= @listing.price %>円（一名様あたり）</span>
                        </div>

                        <div class="panel-body panel-real">
                            <%= form_for [@listing, @listing.reservations.new] do |f| %>

                                <!-- 予約するときに一緒に送るデータ -->
                                <%= f.hidden_field :listing_id, value: @listing.id %>
                                <%= f.hidden_field :participants, number: 'reservation_participants' %>
                                <!-- <%= f.hidden_field :adults, number: 'reservation_adults' %>
                                <%= f.hidden_field :children, number: 'reservation_children' %>
                                <%= f.hidden_field :infants, number: 'reservation_infants' %> -->
                                <%= f.hidden_field :price, value: @listing.price %>
                                <!-- <%= f.hidden_field :commission, value:'reservation_commision'  %> -->
                                <%= f.hidden_field :total_price, id:'reservation_total_price' %>

                                <div class="row row-space-3">
                                  <div class="col-md-12">
                                    <label>日にち</label>
                                      <%= f.text_field :date, :class => 'form-control', placeholder: 'yyyy/mm/dd' %>
                                  </div>
                                </div>

                                <div class="row row-space-3">
                                  <div class="col-md-12">
                                    <label>参加者</label>
                                      <%= f.text_field :participants, :class => 'form-control', placeholder: '参加者数' %>
                                  </div>
                                </div>

                                <div class="actions text-center">
                                  <%= f.submit "予約する", class: "btn btn-danger btn-wide" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<!-- メインサマリー -->
<div class="container">
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">このプログラムについて</h3>
          <p><%= simple_format(@listing.summary) %>
          </p>
      </div>

      <div class="col-md-3">

      </div>
    </div>

      <!-- 定員 -->
      <div class="row">
        <div class="col-md-9">
          <h3 class="row-space-3">定員</h3>
          <p><%= @listing.capacity %>名</p>
        </div>

        <div class="col-md-3">

        </div>
      </div>

    <!-- 対応言語 -->
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">対応言語</h3>
        <p><%= simple_format(@listing.language) %>
        </p>
      </div>

      <div class="col-md-3">

      </div>
    </div>

    <!-- タイムスケジュール -->
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">タイムスケジュール</h3>
        <p><%= simple_format(@listing.time_schedule) %>
        </p>
      </div>

      <div class="col-md-3">

      </div>
    </div>

    <!-- 含まれるもの -->
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">含まれるもの</h3>
        <p><%= simple_format(@listing.price_include) %>
        </p>
      </div>

      <div class="col-md-3">

      </div>
    </div>

    <!-- 当日の持ち物 -->
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">当日の持ち物</h3>
        <p><%= simple_format(@listing.to_bring) %>
        </p>
      </div>

      <div class="col-md-3">

      </div>
    </div>

    <!-- レビュー -->
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">レビュー</h3>
      </div>

      <div class="col-md-3">

      </div>
    </div>

    <!-- google map -->
    <div class="row">
        <div class="col-md-9">
          <h3 class="row-space-3">アクセス</h3>
          <div id="map"></div>
        </div>

        <div class="col-md-3">

        </div>
    </div>
    <style>
      #map {
        width: 100%;
        height: 350px;
      }
    </style>

    <!-- 周辺ののプログラム -->
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">周辺のプログラム</h3>

        <% for listing in @listing.nearbys(10) %>
          <div class="col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading panel-listing text-center" style="padding: 0;">
                <%= link_to(listing) do %>
                    <%= image_tag listing.photos[0].image.url(:medium)  if listing.photos.length > 0 %>
                <% end %>
              </div>

              <div class="panel-body">
                <div class="row">
                  <div class="col-md-8 col-xs-8">
                      <%= link_to listing.title, listing %><br>
                  </div>
                  <div class="col-md-3 col-xs-3">
                    <% if listing.user.image.present? %>
                      <%= image_tag listing.user.image,class:"img-circle profile-1" %>
                    <% end %>
                  </div>
                  <div class="price-card">
                      <%= listing.price %> 円
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-md-3">
      </div>
  </div>
</div>

<script>
function initMap() {

  // Create the map.
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,
    center: {lat: <%= @listing.latitude %>, lng:<%= @listing.longitude %>},
    mapTypeId: google.maps.MapTypeId.TERRAIN
  });

  // Add the circle for this city to the map.
  var cityCircle = new google.maps.Circle({
    strokeColor: '#FD8524',
    strokeOpacity: 0.6,
    strokeWeight: 2,
    fillColor: '#FD8524',
    fillOpacity: 0.4,
    map: map,
    center: {lat: <%= @listing.latitude %>, lng:<%= @listing.longitude %>},
    radius: 400
  });

}

</script>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAULbikEu4O6oHV0Ek8uvQhnWWQDgSPj5o&signed_in=true&callback=initMap">
</script>

<script>
  $( function() {
    $( "#reservation_date" ).datepicker();
  } );
</script>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>

app/views/pages/index.html.erb
<script type="text/javascript">
  $(function(){
    $(".navbar").removeClass("navbar-devise");
    $(".navbar").addClass("navbar-default");
  });
</script>

<div class="jumbotron">
  <%= render 'partial/navbar' %>

  <div class="container">
   <div class="row">
     <div class="col-md-6 col-md-offset-3 text-center">
       <h1 class="display-3">Hello, world!</h1>
     </div>
   </div>
  </div>
</div>

<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/partial/_deviseErrorMsg.html.erb
<!-- deviseにエラーがある場合 -->
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>');
		<% end %>
	</script>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-devise">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">WellnessGuide</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
          <!-- ログインしていない時 -->
          <li><%= link_to "ウェルネスガイドになる", new_listing_path %></li>
          <li><a href="#">ご利用の流れ</a></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% else %>
          <!-- ログインしている時 -->
          <li><%= link_to "ウェルネスガイドになる", new_listing_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <% if current_user.provider %>
                <!-- 認証ログインをしている時 -->
                <%= image_tag current_user.image, class:"img-circle profile-0" %>
                <%= current_user.name %>
              <% else %>
                <!-- 認証ログインしていない時 -->
                <% if current_user.image.present? %>
        					<%= image_tag current_user.image, class: "profile-full img-circle" %>
        				<% end %>
                <% if current_user.name.present? %>
                  <%= current_user.name %>
                <% else %>
                  <%= current_user.email.split("@")[0] %>
                <% end %>

              <% end %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", user_path(current_user) %></li>
              <li><%= link_to "プロフィール編集", edit_user_registration_path %></li>
              <li><%= link_to "プログラム管理", listings_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partial/_verticalnavbar.html.erb
<div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <label style="color: #fff;">他の項目を編集する</label>
      </button>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller?("listings") && action?("basics") %>">
          <%= link_to "基本情報", manage_listing_basics_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("description") %>">
          <%= link_to "プログラム内容", manage_listing_description_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("meeting_place") %>">
          <%= link_to "実施場所", manage_listing_meeting_place_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("price") %>">
          <%= link_to "料金", manage_listing_price_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("photos") %>">
          <%= link_to "プログラム画像", manage_listing_photos_path(@listing), data:{turbolinks:false} %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("calendar") %>">
          <%= link_to "カレンダー", manage_listing_calendar_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("bankacccount") %>">
          <%= link_to "受取口座情報", manage_listing_bankaccount_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("publish") %>">
          <%= link_to "公開する", manage_listing_publish_path(@listing) %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>